/**
 * Summary: Centralizes product-default-language copy for read-only Plan inspection.
 * Why: Keeps M2 state and recovery wording consistent across list and detail routes.
 */
export const planCopy = {
  list: {
    eyebrow: "Inspection",
    title: "Plans",
    description:
      "Browse recorded Plans and inspect their stored actions without changing library files.",
    searchLabel: "Search Plans",
    searchPlaceholder: "Plan ID, Library ID, type, or status",
    statusLabel: "Plan status",
    typeLabel: "Plan type",
    blockedLabel: "Has blocked actions",
    allStatuses: "All statuses",
    allTypes: "All types",
    resetFilters: "Reset filters",
    loading: "Loading Plans…",
    loadingMore: "Loading more Plans…",
    loadMore: "Load more Plans",
    emptyTitle: "No Plans match these filters",
    emptyBody:
      "Try changing the search or filters to inspect other recorded Plans.",
    noPlansTitle: "No Plans have been recorded",
    noPlansBody:
      "Recorded Plans will appear here when planning becomes available.",
    retry: "Try again",
    loadError: "Plans could not be loaded",
    resultCount: "matching Plans",
  },
  detail: {
    eyebrow: "Plan inspection",
    title: "Plan detail",
    back: "Back to Plans",
    loading: "Loading Plan detail…",
    loadingActions: "Loading recorded actions…",
    loadingGroups: "Loading action groups…",
    loadingFacets: "Loading action facets…",
    notFoundTitle: "Plan not found",
    notFoundBody:
      "This Plan is not available in the recorded inspection data. Check the full Plan ID and try again.",
    retry: "Try again",
    loadError: "Plan inspection could not be loaded",
    summary: "Recorded action summary",
    actions: "Recorded actions",
    actionGroups: "Action groups",
    facets: "Action facets",
    actionSearchLabel: "Search recorded actions",
    actionSearchPlaceholder: "Action ID, Track ID, path, or recorded hash",
    actionStatusLabel: "Action status",
    actionTypeLabel: "Action type",
    reasonLabel: "Recorded reason",
    groupingLabel: "Group actions by",
    allActionStatuses: "All action statuses",
    allActionTypes: "All action types",
    allReasons: "All recorded reasons",
    clearActionFilters: "Reset action filters",
    clearGroup: "Clear group selection",
    selectedGroup: "Selected group",
    targetCollisions: "Recorded target collisions",
    actionCount: "recorded actions",
    noActions: "This Plan has no recorded actions.",
    noGroups: "No action groups are available for this Plan.",
    noFacets: "No action facets are available for this Plan.",
    loadMoreGroups: "Load more action groups",
    loadingMoreGroups: "Loading more action groups…",
    loadMoreActions: "Load more actions",
    loadingMoreActions: "Loading more actions…",
  },
  labels: {
    identifier: "Plan ID",
    library: "Library ID",
    created: "Created",
    status: "Status",
    type: "Type",
    total: "Total",
    planned: "Planned",
    blocked: "Blocked",
    applied: "Applied",
    failed: "Failed",
    move: "Move",
    skip: "Skip",
    refreshMetadata: "Refresh metadata",
    actionId: "Action ID",
    trackId: "Track ID",
    sourcePath: "Source path",
    targetPath: "Target path",
    actionType: "Action type",
    reason: "Reason",
    group: "Group",
    count: "Count",
    blockedCount: "Blocked",
    topReason: "Most common reason",
  },
  unknown: {
    status: "Unknown status",
    type: "Unknown type",
    actionType: "Unknown action type",
    reason: "Unknown reason",
    grouping: "Unknown grouping",
  },
} as const;
