/**
 * Summary: Centralizes product-default-language copy for Plan review and execution.
 * Why: Keeps recorded evidence, capability, and recovery wording consistent.
 */
import type {
  ArtistNameResolutionIssue,
  ArtistNameResolutionProvenance,
} from "../../api/generated";

export const planCopy = {
  list: {
    eyebrow: "Inspection",
    title: "Plans",
    description:
      "Browse recorded Plans and inspect their stored actions without changing library files.",
    searchLabel: "Search Plans",
    searchPlaceholder: "Plan ID, Library ID, type, or status…",
    statusLabel: "Plan status",
    typeLabel: "Plan type",
    blockedLabel: "Has blocked actions",
    allStatuses: "All statuses",
    allTypes: "All types",
    resetFilters: "Reset filters",
    loading: "Loading Plans…",
    emptyTitle: "No Plans match these filters",
    emptyBody:
      "Try changing the search or filters to inspect other recorded Plans.",
    noPlansTitle: "No Plans have been recorded",
    noPlansBody:
      "Create an Add, Organize, Refresh, or Undo Plan to begin reviewable work.",
    loadError: "Plans could not be loaded",
    resultCount: "matching Plans",
  },
  detail: {
    eyebrow: "Plan inspection",
    title: "Plan detail",
    back: "Back to Plans",
    loading: "Loading Plan detail…",
    loadingActions: "Loading recorded actions…",
    loadingGroups: "Loading action groups…",
    loadingFacets: "Loading action facets…",
    notFoundTitle: "Plan not found",
    notFoundBody:
      "This Plan is not available in the recorded inspection data. Check the full Plan ID and try again.",
    loadError: "Plan inspection could not be loaded",
    summary: "Recorded action summary",
    actions: "Recorded actions",
    actionGroups: "Action groups",
    facets: "Action facets",
    actionSearchLabel: "Search recorded actions",
    actionSearchPlaceholder: "Action ID, Track ID, path, or recorded hash…",
    actionStatusLabel: "Action status",
    actionTypeLabel: "Action type",
    reasonLabel: "Recorded reason",
    groupingLabel: "Group actions by",
    allActionStatuses: "All action statuses",
    allActionTypes: "All action types",
    allReasons: "All recorded reasons",
    clearActionFilters: "Reset action filters",
    clearGroup: "Clear group selection",
    selectedGroup: "Selected group",
    targetCollisions: "Recorded target collisions",
    actionCount: "recorded actions",
    noActions: "This Plan has no recorded actions.",
    noGroups: "No action groups are available for this Plan.",
    noFacets: "No action facets are available for this Plan.",
    artistNameDiagnostics: "Artist naming",
  },
  execution: {
    title: "Plan execution",
    description:
      "Use the backend-authoritative controls below. Availability is rechecked when a request is accepted.",
    apply: "Apply Plan",
    startingApply: "Starting Apply…",
    cancel: "Cancel Plan",
    cancelDialogTitle: "Cancel this Plan?",
    cancelDialogBody:
      "Cancellation is permanent for this ready Plan. No library music files will be changed.",
    cancelDialogConfirm: "Cancel this Plan",
    cancelDialogDismiss: "Keep Plan",
    cancelDialogClose: "Close cancellation confirmation",
    cancelling: "Cancelling…",
    recreate: "Create a new Plan from the current state",
    activeOperation: "Recover active Operation",
    noBootstrap:
      "Execution controls need the local startup token. Restore the service and reload this Plan.",
    applyError: "Apply could not be started",
    cancelError: "Plan could not be cancelled",
    cancelledAnnouncement: "Plan cancelled. Execution controls updated.",
    historyResult: "Open completed Run in History",
    blockedOnly:
      "Every recorded action is blocked. Apply is still available when the backend permits it, but this Plan will not mutate a library file.",
    mixedBlocked: (count: number) =>
      `${count} blocked ${count === 1 ? "action remains" : "actions remain"} unresolved. Apply will process only the recorded executable actions.`,
  },
  labels: {
    identifier: "Plan ID",
    library: "Library ID",
    created: "Created",
    status: "Status",
    type: "Type",
    planned: "Planned",
    blocked: "Blocked",
    applied: "Applied",
    failed: "Failed",
    move: "Move",
    moveLyrics: "Move lyrics",
    moveArtwork: "Move artwork",
    moveUnprocessed: "Move unprocessed",
    skip: "Skip",
    refreshMetadata: "Refresh metadata",
    trackId: "Track ID",
    companionAssetId: "Companion asset ID",
    ownerActionId: "Owner action ID",
    dependencyActionIds: "Depends on action IDs",
    sourcePath: "Source path",
    targetPath: "Target path",
    actionType: "Action type",
    reason: "Reason",
    topReason: "Most common reason",
    artist: "Artist",
    albumArtist: "Album artist",
    provenance: "Provenance",
    issue: "Issue",
  },
  artistNames: {
    noIssue: "None",
    provenance: {
      user_preference: "User preference",
      accepted_musicbrainz: "Accepted MusicBrainz result",
      new_musicbrainz: "New MusicBrainz result",
      original: "Original metadata",
    } satisfies Record<ArtistNameResolutionProvenance, string>,
    issue: {
      missing_source: "Missing source name",
      composite_unsupported: "Composite name unsupported",
      non_latin_required: "Source contains Latin text",
      detector_unavailable: "Language detector unavailable",
      automatic_lookup_disabled: "Automatic lookup disabled",
      not_japanese: "Not detected as Japanese",
      low_language_confidence: "Low language confidence",
      provider_unavailable: "MusicBrainz unavailable",
      no_confident_match: "No confident match",
      ambiguous_match: "Ambiguous match",
    } satisfies Record<ArtistNameResolutionIssue, string>,
  },
} as const;
